### ISSUE TITLE
article headings' highlighting should move accordingly 

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#10]
-  highlighting (turquoise line) should move to a heading where user just navigated (via sidebar menu) or by scrolling
SO:

1. user clicks on an item in the sidebar - highlighting moves under the item on the sidebar and in the article 
2. user scrolls through article - highlighting moves on the sidebar and in the article accordingly to where the user is 

- highlighting size adjusts to the length of the heading

<img width="952" alt="screen shot 2017-10-30 at 10 34 16" src="https://user-images.githubusercontent.com/32299247/32164032-86a4b1b4-bd5e-11e7-8825-8444113a6ee9.png">

**Comment by agnespisz** [comment]
please check as well:
when you navigate to a heading from sidebar menu, the article moves not exactly to the place in the article (it moves directly to text, heading is not visible :( )

**Comment by marcin-wosinek** [comment]
the comment side will be addressed in #22

**Comment by marcin-wosinek** [comment]
Pretty likely time sink - in development & later on in maintenance (ie. fixing when ever gets broken when ever content is being updated).

For me it looks like a candidate for being postponed - until we will have all content put in; and we will have enough blog posts to be sure that:
https://eapoland.github.io/landing-page/blog/post-1.html

doesn't need side bar.

**Comment by agnespisz** [comment]
blog posts will not have sidebar - they will have only sharing bar. 

So it's needed only on Zacznij działać i Czym jest EA. 

Can we at least bold the sections on sidebar menu and in the article, when chosen or scrolled to?

**Comment by marcin-wosinek** [comment]
probably to be addressed with:
https://getbootstrap.com/docs/4.0/components/navs/

**Comment by agnespisz** [comment]
I guess so!

**Comment by marcin-wosinek** [comment]
To be checked at:
https://eapoland.github.io/landing-page/czym-jest-ea.html#heading4

the same thing will be applied to /zacznij-dzialac.html *after* GH-20
