### ISSUE TITLE
BLOG: lista wpisów 

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#11]
- list of posts should look like our current subpage 'o ruchu'

<img width="1112" alt="screen shot 2017-10-30 at 10 50 37" src="https://user-images.githubusercontent.com/32299247/32164515-0ed1e196-bd60-11e7-942e-863871c54472.png">

- remove buttons
- link heading as a main navigator to the post
- snippet of a post - let's limit showed part of the beginning of a post and finish it with '...' 
- below the post snippet, let's add 'added [date]

**Comment by marcin-wosinek** [comment]
The list will be generated automatically later on. Current, final view:
![screenshot from 2017-11-19 19-21-27](https://user-images.githubusercontent.com/1024920/32993871-e68f1000-cd5e-11e7-9690-c1fd4d1e15bd.png)
