### ISSUE TITLE
BLOG: post look

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#12]
Let's clone the look of the article 'czym jest EA?' for blog post

<img width="982" alt="screen shot 2017-10-30 at 11 16 15" src="https://user-images.githubusercontent.com/32299247/32165589-904f2ec4-bd63-11e7-988b-adb5355eb78d.png">

- center the main body (needed after removing sidebar menu)
- in place of sidebar menu - let's do the 'sharing bar' (examples below - but let's discuss what we can use)

<img width="340" alt="screen shot 2017-10-30 at 11 22 31" src="https://user-images.githubusercontent.com/32299247/32165856-67f21d82-bd64-11e7-9426-0ecacc22e6c5.png">
<img width="129" alt="screen shot 2017-10-30 at 11 21 49" src="https://user-images.githubusercontent.com/32299247/32165866-6b61678e-bd64-11e7-8b8d-38ef3772a280.png">

- add 'posted on [date]'  between heading and post text

**Comment by marcin-wosinek** [comment]
To be worked on at:
https://eapoland.github.io/landing-page/blog-post-1.html

**Comment by agnespisz** [comment]
1. remove turquoise line from default state - show it on mouse hover.  Remove underline on hover of the heading. 

<img width="364" alt="screen shot 2017-11-11 at 16 52 53" src="https://user-images.githubusercontent.com/32299247/32690988-d01f23f0-c700-11e7-8196-c581d11f0450.png">


2. Let's cut half the introcopy

**Comment by agnespisz** [comment]
1. Add breadcrumb
- 'Lista wpisów' treated as link 
2. Add date of publication
- keep adequate space between heading+date and copy 

![screen shot 2017-11-11 at 16 59 28](https://user-images.githubusercontent.com/32299247/32691082-d4c6708c-c702-11e7-90b8-c6ddc61249fc.jpg)

**Comment by agnespisz** [comment]
linkowanie z loga na główną stronę nie działa. (tylko w poście)

**Comment by agnespisz** [comment]
also when I create a link to the subpage, it doesn't work. (look at 'napisz do nas' at the last part of the post).

**Comment by marcin-wosinek** [comment]
linking is fixed.

**Comment by marcin-wosinek** [comment]
bread crumb added, the rest please move to new tickets
![screenshot-2017-11-19 efektywny altruizm 1](https://user-images.githubusercontent.com/1024920/32994062-684bfd1c-cd62-11e7-953a-29d58eb99d45.png)

**Comment by agnespisz** [comment]
Align breadcrumb with the rest of the elements, please

**Comment by agnespisz** [comment]
breadcrumb is hiding on mobile ;)


![img_2151](https://user-images.githubusercontent.com/32299247/33018367-679ee656-cdf6-11e7-8a9a-068a4432bb4c.PNG)

**Comment by marcin-wosinek** [comment]
changed.

please open a new ticket if there some other changes, where we have already 4 pages of content that one needs to scan to figure out what change is meant.
