### ISSUE TITLE
Issues for mobile

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#13]
# 1. Let's align main body text to the left

![img_2066](https://user-images.githubusercontent.com/32299247/32611844-fa16276c-c566-11e7-82fb-6000b22df8ab.PNG)

# 2.  this is what happens when I zoom out the website. Can't be :) 

![img_2067](https://user-images.githubusercontent.com/32299247/32611891-19c469ac-c567-11e7-85d5-e073652e4e54.PNG)

# 3. Sections with photos should be centred. 

![img_2064](https://user-images.githubusercontent.com/32299247/32611950-3b932154-c567-11e7-9ef3-ffe93f7afa57.PNG)

**Comment by marcin-wosinek** [comment]
@agnespisz 

1. is ready to tested
2. looks reasonable for deviced that support zooming out of the page;) what is it, safari? I think how to address it, without turning off the zooming what-so-ever - zooming in is useful, and on my android's chrome it's working ok.

**Comment by marcin-wosinek** [comment]
3. ready to be tested

**Comment by agnespisz** [comment]
jest git, zamykam.
