### ISSUE TITLE
figure out how to send email from static page

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#15]
https://eapoland.github.io/landing-page/napisz-do-nas.html

is not connected to anything that sends email. We need some kind of service that i can send a request to; or replace by google form or something similar.

**Comment by marcin-wosinek** [comment]
https://formspree.io/

> Formspree is free for 1000 submissions per email each month. If you need more, there's a Gold Plan.

sounds like our case:)

**Comment by marcin-wosinek** [comment]
@michaltrzesimiech & @agnespisz what email should we send to?

**Comment by marcin-wosinek** [comment]
https://eapoland.github.io/landing-page/napisz-do-nas.html sends to my email

**Comment by agnespisz** [comment]
you can rather add my email ;)

**Comment by agnespisz** [comment]
how it will all work? 
This is what I see after 'send msg' in our form
![img_2152](https://user-images.githubusercontent.com/32299247/33018434-ac9417b8-cdf6-11e7-9f93-534f375d3193.PNG)

**Comment by marcin-wosinek** [comment]
first email that leaves the page has to be confirmed by recipient. You can change the recipient here:
https://github.com/eapoland/landing-page/blob/master/src/pages/napisz-do-nas.html#L13

or tell me the address you mean (agnes.pisz@gmail.com ?)
