### ISSUE TITLE
Shadow on hover behind fb icon

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#17]
Add  light shadow on mouse hover for FB icon 

<img width="469" alt="screen shot 2017-11-11 at 15 35 39" src="https://user-images.githubusercontent.com/32299247/32690387-399f46a8-c6f6-11e7-8176-c2f536151d2d.png">

**Comment by marcin-wosinek** [comment]
at:
https://eapoland.github.io/landing-page/polska-spolecznosc.html

**Comment by marcin-wosinek** [comment]
we probably need transparent logo for that:
![screenshot-2017-11-12 efektywny altruizm](https://user-images.githubusercontent.com/1024920/32700873-9d8d80aa-c7cb-11e7-8707-cb564cf11142.png)

**Comment by marcin-wosinek** [comment]
or different visual effect - maybe changing the 'f's color

**Comment by agnespisz** [comment]
will be easier, if I prepare separate version with shadow and it will be appearing on hover?

**Comment by marcin-wosinek** [comment]
yes

**Comment by agnespisz** [comment]
I've added a file fb art copy.png

**Comment by marcin-wosinek** [comment]
`text-shadow:` ! fixed without the image logo

**Comment by marcin-wosinek** [comment]
https://eapoland.github.io/landing-page/polska-spolecznosc.html
