### ISSUE TITLE
mobile: some parts layer each other

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#18]
Look at 'Zobacz więcej' ;)

![img_2099](https://user-images.githubusercontent.com/32299247/32978669-45d045e8-cc47-11e7-9ee6-304bc9404d9d.PNG)

**Comment by marcin-wosinek** [comment]
![screenshot-2017-11-19 efektywny altruizm](https://user-images.githubusercontent.com/1024920/32993996-12f9ac8e-cd61-11e7-8adb-f2ebcb820eaa.png)
