### ISSUE TITLE
Pl społeczność: Zaangażowani section to rebuild

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#19]
We need to rebuild Zaangażowani section. 
- create 3 subsections where we will be able to add personas 

mockup
![zaangazowani sections](https://user-images.githubusercontent.com/32299247/32979011-647423c4-cc4d-11e7-8dcc-ce022c1e1e15.png)

**Comment by marcin-wosinek** [comment]
![screenshot-2017-11-18 efektywny altruizm](https://user-images.githubusercontent.com/1024920/32984413-77f6abe8-cca6-11e7-95b3-851c3c2cc64b.png)

https://eapoland.github.io/landing-page/polska-spolecznosc.html

**Comment by agnespisz** [comment]
w tym przypadku powinny iść od lewej, tak jak na makiecie

**Comment by marcin-wosinek** [comment]
Zmienione:
https://eapoland.github.io/landing-page/polska-spolecznosc.html

centrowanie z #13 ograniczyłem do mobilnych.
