### ISSUE TITLE
Zacznij działać page: Add 'Pokaż więcej' option to the article subsections

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#20]
1. Add 'Pokaż więcej/Pokaż mniej' option to particular sections. 
The best will be if I could manipulate where it's placed. 

Mockup
![zacznij dzialac](https://user-images.githubusercontent.com/32299247/32979221-615f2964-cc51-11e7-908f-6892575b3ad4.png)

**Comment by marcin-wosinek** [comment]
is it really a release blocker? sounds more like bells & whistles to me.

**Comment by agnespisz** [comment]
it is. We can't give first users never ending scrolling - there will be huge amount of copy.

**Comment by marcin-wosinek** [comment]
something like this:
https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

?

**Comment by agnespisz** [comment]
yes, toggle item.

**Comment by marcin-wosinek** [comment]
first section moved

![accordian](https://user-images.githubusercontent.com/1024920/33513985-1beb6a54-d74c-11e7-9cd6-32e1ae595e33.png)

https://eapoland.github.io/landing-page/zacznij-dzialac.html#heading1

@agnespisz please review & let me know if you want the same thing in other place on that page too

**Comment by agnespisz** [comment]
hey, I meant this one:
<img width="894" alt="screen shot 2017-12-02 at 10 57 47" src="https://user-images.githubusercontent.com/32299247/33514182-b0177b7a-d74f-11e7-9c25-e3f728baa06f.png">
also the one you applied has changed copy styling

**Comment by agnespisz** [comment]
as on the mockup: we toggle only some part of the section, not the whole section.

**Comment by agnespisz** [comment]
https://q5c77p.axshare.com/#c=2   clickable mockup

**Comment by agnespisz** [comment]
![sekcje](https://user-images.githubusercontent.com/32299247/33543453-617549e6-d8d7-11e7-9c5f-25ca7e1eb4d7.png)
 
dodaje jeszcze resztę sekcji, dodam je osobno jak skończę

**Comment by marcin-wosinek** [comment]
I updated last section on:
https://eapoland.github.io/landing-page/zacznij-dzialac.html

if all is OK, let me know & I will continue with the rest of sections as defined on the image above.

**Comment by agnespisz** [comment]
awesome :) 
the only things:
1. locate it more in the next line of paragraph, not further (now it's closer to the hidden part of paragraph
2. can we use this arrow? ;)  (I will add it to the files)
![strzalka down](https://user-images.githubusercontent.com/32299247/33604655-0739a270-d9b7-11e7-8fb7-cb3b71c26e99.png)

**Comment by agnespisz** [comment]
ah, and it's not clickable on mobile yet :)

**Comment by agnespisz** [comment]
all subsections added

**Comment by marcin-wosinek** [comment]
at what device it doens't work? I've checked on a simulator on desk top chrome & in androids chrome & both worked fine

**Comment by marcin-wosinek** [comment]
the arrow will be addressed in  #25

**Comment by marcin-wosinek** [comment]
I've made collapsible other section (second from the bottom). Feel free to help if pattern of changes are clear:
https://github.com/eapoland/landing-page/commit/7b640d9ac080449b8af736c1eecd1156fb40838a

in case of any general, visual issue feel free to register a new ticket & add the milestones accordingly

**Comment by marcin-wosinek** [comment]
@agnespisz on the way to:
https://eapoland.github.io/landing-page/zacznij-dzialac.html

**Comment by agnespisz** [comment]
please don't forget about this comment :) <img width="731" alt="screen shot 2017-12-09 at 13 30 43" src="https://user-images.githubusercontent.com/32299247/33795618-301bde7a-dce5-11e7-90f1-149102000b4b.png">

**Comment by marcin-wosinek** [comment]
isn't it meant to be addressed in #25 ?
