### ISSUE TITLE
sharing bar on the rightside of the blog post 

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#21]
- in place of sidebar menu - let's do the 'sharing bar' (examples below - but let's discuss what we can use)

<img width="340" alt="screen shot 2017-10-30 at 11 22 31" src="https://user-images.githubusercontent.com/32299247/32165856-67f21d82-bd64-11e7-9426-0ecacc22e6c5.png">
<img width="129" alt="screen shot 2017-10-30 at 11 21 49" src="https://user-images.githubusercontent.com/32299247/32165866-6b61678e-bd64-11e7-8b8d-38ef3772a280.png">

**Comment by marcin-wosinek** [comment]
* Fb
* Twitter
* linkedin
* kopiuj link na klik,

**Comment by agnespisz** [comment]
kiedy możemy z tym podziałać? :)

**Comment by marcin-wosinek** [comment]
wciaż mamy w polityce prywatności:

> Dane kontaktowe
> Efektywny Altruism PL
> ea@pl.pl
> Lorem Ipsum 

100% śledzenia (powodu dla którego potrzebujemy polityki prywatności) to zewnętrze integracje (hotjar, social guziki, google analitics); ja bym się nie śpieszył, aż będziemy mieć oficjalne dane fundacji.

**Comment by agnespisz** [comment]
faktycznie! zapomniałam, że to zależne od tego.
