### ISSUE TITLE
scroll position issue

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#22]
> when you navigate to a heading from sidebar menu, the article moves not exactly to the place in the article (it moves directly to text, heading is not visible :( )

**Comment by marcin-wosinek** [comment]
addressed:
https://eapoland.github.io/landing-page/zacznij-dzialac.html#heading1

**Comment by agnespisz** [comment]
Marcinie! I changed visuals of the headings and I broke it again :( I will not change the visual of those headings anymore!!

**Comment by marcin-wosinek** [comment]
fixed
