### ISSUE TITLE
Pl Społeczność: arrow disappeared

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#23]
pokaż więcej/pokaż mniej arrow disappeared

<img width="231" alt="screen shot 2017-11-21 at 11 47 39" src="https://user-images.githubusercontent.com/32299247/33068493-d6e62216-ceb1-11e7-9971-9ff439e43e76.png">

**Comment by agnespisz** [comment]
try to align dashed line properly so that photos are not cut 

<img width="685" alt="screen shot 2017-11-23 at 13 52 50" src="https://user-images.githubusercontent.com/32299247/33173798-bb855fb4-d055-11e7-8535-d3af52b52752.png">

**Comment by marcin-wosinek** [comment]
at https://eapoland.github.io/landing-page/polska-spolecznosc.html
