### ISSUE TITLE
Get back to primary styling 

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#24]
Be back to basic styling - after those changes, it changed font. 

<img width="1070" alt="screen shot 2017-12-04 at 09 44 05" src="https://user-images.githubusercontent.com/32299247/33543545-b8f5501c-d8d7-11e7-9da1-8f80d02446a6.png">

**Comment by marcin-wosinek** [comment]
Fixed at:
https://eapoland.github.io/landing-page/
