### ISSUE TITLE
change the read more arrow

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#25]
use `src/images/arrow-down.png`
create similar one for up

**Comment by agnespisz** [comment]
![strzalka up](https://user-images.githubusercontent.com/32299247/33707159-c66b44a2-db36-11e7-8d4a-ec8a4eecaad4.png)

**Comment by agnespisz** [comment]
yeah ok so I add it here

<img width="731" alt="screen shot 2017-12-09 at 13 30 43" src="https://user-images.githubusercontent.com/32299247/33795681-4a335af8-dce6-11e7-8ed7-ced034334866.png">

**Comment by marcin-wosinek** [comment]
on the way to https://eapoland.github.io/landing-page/zacznij-dzialac.html#heading1

**Comment by agnespisz** [comment]
that's what I meant in a comment, can we handle this with <p></p> structure?

<img width="497" alt="screen shot 2017-12-09 at 22 23 44" src="https://user-images.githubusercontent.com/32299247/33799648-2ae5b728-dd30-11e7-875b-aeb57adb75a8.png">

**Comment by marcin-wosinek** [comment]
It will be addressed with #28
