### ISSUE TITLE
'pokaz wiecej' doesn't work on iphone screen

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#26]
'pokaz wiecej' doesn't work on iphone screen

**Comment by marcin-wosinek** [comment]
you mean tapping on it doens't open the section, right?

**Comment by agnespisz** [comment]
yes sir.

**Comment by marcin-wosinek** [comment]
https://eapoland.github.io/landing-page/zacznij-dzialac.html#heading3

**Comment by marcin-wosinek** [comment]
I cannot reproduce at http://ipadpeek.com/; I'm looking for other ways to investigate it

**Comment by marcin-wosinek** [comment]
It's broken www.browserstack.com's iPad Air

**Comment by marcin-wosinek** [comment]
on the way to:
https://eapoland.github.io/landing-page/zacznij-dzialac.html

please check on iDevice & close if works ok.
