### ISSUE TITLE
Add 'pokaż więcej' to those sections

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#29]
<img width="566" alt="screen shot 2017-12-10 at 17 03 57" src="https://user-images.githubusercontent.com/32299247/33806721-7e20e718-ddcc-11e7-9814-beef0d000b1c.png">
<img width="565" alt="screen shot 2017-12-10 at 17 04 21" src="https://user-images.githubusercontent.com/32299247/33806722-7e40472a-ddcc-11e7-89a6-3b67b67da737.png">
<img width="567" alt="screen shot 2017-12-10 at 17 04 32" src="https://user-images.githubusercontent.com/32299247/33806723-7e625d88-ddcc-11e7-8912-73105b3aa89c.png">

**Comment by marcin-wosinek** [comment]
on the way to https://eapoland.github.io/landing-page/zacznij-dzialac.html
