### ISSUE TITLE
DNS dla beta.efektywnyaltruizm.org 

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#3]
skonfigurować DNS dla beta.efektywnyaltruizm.org; żebyśmy mieli ładny adres do:
http://ec2-54-70-8-69.us-west-2.compute.amazonaws.com/beta_efektywnyaltruizm_org/

**Comment by marcin-wosinek** [comment]
@michaltrzesimiech

**Comment by michaltrzesimiech** [comment]
zrobione

**Comment by marcin-wosinek** [comment]
http://www.dnsqueries.com/en/dns_lookup.php dla:
* efektywnyaltruizm.org zwraca 
A | 54.70.8.69
* beta.efektywnyaltruizm.org zwraca
`No results found for hostname beta.efektywnyaltruizm.org query type A`

**Comment by marcin-wosinek** [comment]
```
[~]
marcin-> nslookup efektywnyaltruizm.org  
Server:         127.0.1.1
Address:        127.0.1.1#53

Non-authoritative answer:
Name:   efektywnyaltruizm.org
Address: 54.70.8.69

[~]
marcin-> nslookup beta.efektywnyaltruizm.org 
Server:         127.0.1.1
Address:        127.0.1.1#53

** server can't find beta.efektywnyaltruizm.org: NXDOMAIN
```

**Comment by marcin-wosinek** [comment]
@michaltrzesimiech ping

**Comment by michaltrzesimiech** [comment]
Isolated and fixed the issue. beta.efektywnyaltruizm.org should now point to 

> "http://ec2-54-70-8-69.us-west-2.compute.amazonaws.com/beta_efektywnyaltruizm_org/"

instead of 

> "http://http://ec2-54-70-8-69.us-west-2.compute.amazonaws.com/beta_efektywnyaltruizm_org/"
