### ISSUE TITLE
Change logo font to Roboto slab

### ISSUE THREAD

**Issue by michaltrzesimiech** [eapoland/landing-page#30]
Let's change the font used to render the name Efektywny Altruizm to https://fonts.google.com/specimen/Roboto+Slab (default for EA)

**Comment by agnespisz** [comment]
it's almost the same as the used one now. (Merriweather).  Looks better on web, it's also used in a logo on effectivealtruism.org  ;)

**Comment by agnespisz** [comment]
so no worries, everything is intended ;)

**Comment by marcin-wosinek** [comment]
@agnespisz & @michaltrzesimiech when you agree o this, please either leave the ticket open (if we want to change it) or close it (if not)

**Comment by michaltrzesimiech** [comment]
I meant the font used to render the text "Efektywny Altruizm" that mocks
our logo. Both our logo and the one used on effectivealtruism.org are
rendered with Roboto Slab. Let's to keep our visual identification aligned
with the global community (including our channels on Facebook).

On 14 Dec 2017 7:37 pm, "agnespisz" <notifications@github.com> wrote:

it's almost the same as the used one now. (Merriweather). Looks better on
web, it's also used in a logo on effectivealtruism.org;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eapoland/landing-page/issues/30#issuecomment-351798472>,
or mute the thread

**Comment by agnespisz** [comment]
<img width="565" alt="screen shot 2017-12-15 at 17 08 14" src="https://user-images.githubusercontent.com/32299247/34050274-9e44f024-e1ba-11e7-8f2e-c0651d1a12da.png">

**Comment by michaltrzesimiech** [comment]
When I inspect the html, I can see that this logo is not rendered as text,
but as a graphic file in svg format. The tool you're using probably
indicates the css style relevant for that section, but font styles apply to
text only. It looks that Merriweather is being used in other sections of
that page, but definitely not in the logo.

We can either use a graphic file or change the font style to Roboto Slab
(you'll see that both logos will become more similar if not identical).

On 15 Dec 2017 5:08 pm, "agnespisz" <notifications@github.com> wrote:

[image: screen shot 2017-12-15 at 17 08 14]
<https://user-images.githubusercontent.com/32299247/34050274-9e44f024-e1ba-11e7-8f2e-c0651d1a12da.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eapoland/landing-page/issues/30#issuecomment-352044192>,
or mute the thread

**Comment by agnespisz** [comment]
ok, right. 

Let's add Roboto Slab to the fonts family and change logo font. 
@marcin-wosinek

**Comment by marcin-wosinek** [comment]
on the way
