### ISSUE TITLE
Font rendering on Linux

### ISSUE THREAD

**Issue by michaltrzesimiech** [eapoland/landing-page#34]
Current font does not render special signs in Polish alphabet when displayed on Linux (tested on Chrome only).

**Comment by marcin-wosinek** [comment]
@justyskaf I guess it's more or less the same issue you've been mentioning.

**Comment by justyskaf** [comment]
Indeed ;)

**Comment by marcin-wosinek** [comment]
I cannot reproduce the issue, nor find any typical issue while reading online.

@michaltrzesimiech & @justyskaf please open the:
* https://eapoland.github.io/landing-page/font.html page
* dev tools (F12 when you are on the page)
* refresh the page with ctrl+r
* save a screen shot like:

![screenshot from 2017-12-21 11-10-53](https://user-images.githubusercontent.com/1024920/34251290-e3583d68-e63f-11e7-9713-8b53aed49d9a.png)

hopefully this will give some clues on what is actually happening. If this will not help, I'll need to screenshare to some of your machines.

**Comment by marcin-wosinek** [comment]
or we are hitting some artefact on scaling the fonts:

![big-font](https://user-images.githubusercontent.com/1024920/34251753-62a0fc26-e641-11e7-83cc-84267847aaa5.png)

big font is displayed as expected, while the same font have some differences between letter with or without accent when scaled down:
![small-font](https://user-images.githubusercontent.com/1024920/34251752-62813fc6-e641-11e7-9ba0-abb345a8906f.png)

here visible between z & ż

**Comment by marcin-wosinek** [comment]
if you open:
https://fonts.google.com/specimen/Open+Sans 

& put `oó źzżzž w  0O b​‌ čcć ​‌d​‌đ​‌  śs​‌š​‌` to styles preview & you scroll the font size, you can see the signs with accents are scaling differently then normal ones.

looks pretty much as a font bug:(

**Comment by marcin-wosinek** [comment]
it doesn't happen in https://fonts.google.com/specimen/Roboto for example (at least not so much)

**Comment by marcin-wosinek** [comment]
nor https://fonts.google.com/specimen/Lato

**Comment by justyskaf** [comment]
[image: image.png]

**Comment by marcin-wosinek** [comment]
@justyskaf could you try again? maybe in the github interface. the attachment didn't arrive here.
