### ISSUE TITLE
something wrong happens with arrow after the change ;)

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#35]
there is a small part of duplicated another one, seems like. 
please check this out :)

<img width="189" alt="screen shot 2017-12-18 at 23 05 12" src="https://user-images.githubusercontent.com/32299247/34130414-fbd1ca0c-e447-11e7-8fbb-80a44187553f.png">

**Comment by marcin-wosinek** [comment]
related to #25

**Comment by marcin-wosinek** [comment]
on way
