### ISSUE TITLE
Dodać polityke prywatności

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#37]
wg generatora z:
https://guideme24.pl/pl/generator-polityki-prywatnoci

* google analitics (dojdzie w #2)
* google adwords - jako klient 
* fb link & share (dojdzie w #21)
*

**Comment by marcin-wosinek** [comment]
@michaltrzesimiech, do polityki prywatności potrzebujemy:

3. Podać dane swojej firmy.

![form](https://user-images.githubusercontent.com/1024920/34377280-9ab955be-eaf0-11e7-87ff-4fcd37850186.png)

**Comment by marcin-wosinek** [comment]
kod do wstawienia na stronę
```
<a href="https://guideme24.pl/privacy-policy/1041" class="guide-embed guide-color-0 guide-branded guide-button-policy" title="Polityka Prywatności" onclick="TINY.box.show({iframe:'https://guideme24.pl/privacy-policy/1041',boxid:'frameless',width:760,height:450,fixed:false}); return false;">Polityka Prywatności</a>

				<script type="text/javascript">
			    (function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0];
			      s.src = "https://guideme24.pl/privacy-policy/client.js"; tag.parentNode.insertBefore(s,tag);};
			      if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}
			      else{w.onload = loader;}})(window, document);
				</script>
```

**Comment by marcin-wosinek** [comment]
https://guideme24.pl/privacy-policy/legal/1041

**Comment by marcin-wosinek** [comment]
@agnespisz - jak to wizualnie ogarniamy? Quick & dirty:
![polityka-prywatnosci](https://user-images.githubusercontent.com/1024920/34379911-1c4d959c-eafe-11e7-89a1-076f139e1763.png)

**Comment by agnespisz** [comment]
Możemy to wrzucić w prawy dolny róg ?

**Comment by marcin-wosinek** [comment]
@agnespisz :
![wide](https://user-images.githubusercontent.com/1024920/34416300-30d14f72-ebf3-11e7-96b9-96dd572267a6.png)
![narrow](https://user-images.githubusercontent.com/1024920/34416301-30ee17ec-ebf3-11e7-8401-0799117a7252.png)

**Comment by agnespisz** [comment]
Jest git!

**Comment by marcin-wosinek** [comment]
ok, idzie na https://eapoland.github.io/landing-page/
