### ISSUE TITLE
Ładowanie normalize.scss z npm

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#4]
@adrianandrzejewski **src/scss/base/_normalize.scss** jest skopiowany skądś bez zmian, czy coś w środku było modyfikowane? **scss_lint** nie lubi:
https://github.com/eapoland/landing-page/blob/master/src/scss/base/_normalize.scss#L65

i prawie zacząłem to zmieniać zanim się skapłem że to chyba zły pomysł

**Comment by adrianandrzejewski** [comment]
Nie pamiętam, ale raczej nic w nim nie zmieniałem. Akurat ta linijka jest zbędna, wywalenie jej nie będzie miało wpływu na działanie strony.

**Comment by marcin-wosinek** [comment]
zamienione na:
https://github.com/JohnAlbin/normalize-scss

**Comment by marcin-wosinek** [comment]
Fail na build. 

Ta sama versja normalize nie ma package.json:
https://github.com/JohnAlbin/normalize-scss/tree/2.1.3

oryginalny _normalize.scss nie jest pakiemte npm:
https://github.com/kristerkari/normalize.scss/blob/master/_normalize.scss

**Comment by marcin-wosinek** [comment]
https://github.com/kristerkari/normalize.scss/issues/21

**Comment by marcin-wosinek** [comment]
was approached again in:
https://github.com/eapoland/landing-page/commit/43059b71a68f59fe9bfcf98b16abc6a94b9b8784
