### ISSUE TITLE
lokalne struktury

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#40]
dodać mapę z zaznaczonymi miastami i linkami do lokalnych struktur (np grupa na fb, etc)

**Comment by marcin-wosinek** [comment]
@agnespisz & @michaltrzesimiech - jakieś opinie, sugestie?

**Comment by agnespisz** [comment]
nie mamy tyle miejsc, by robić specjalnie mapę pod to ;)

**Comment by marcin-wosinek** [comment]
teraz nie, ale jakby przysiąść nad tematem to przybędzie:)

**Comment by agnespisz** [comment]
let's keep it simple now, jak się rozrośniemy to będziemy robić super wizki ;)
