### ISSUE TITLE
Opisać role

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#41]
Opisać zakres obowiązków i cele dla każdej z ról:
* koordynator - lokalnej struktury; projektu
* organizator spoktania
* mentor (w sensie 80000h)
* wolontariusz w projekcie

**Comment by marcin-wosinek** [comment]
@michaltrzesimiech - opinie?

**Comment by marcin-wosinek** [comment]
Tak. Do użytku wewnętrzno/zewnętrznego. Do wyklarowania co robią osoby w poszególnych rolach, tak żeby był punkt odniesienia w przypadku np wymiany w roli 'organizator spotkania' - również w przypadku szukania kogoś nowego do danego zadania.

**Comment by agnespisz** [comment]
dopóki to się nie wyklaruje wewnętrznie, nie będziemy tego dodawać na stronę - tylko w przypadku 'pewnych stanowisk' wśród fundatorów.
