### ISSUE TITLE
Lista przeszłych spotkań

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#42]
Podsumowanie spotkań outreachowych

**Comment by agnespisz** [comment]
jaki masz pomysł na to? dlaczego powinniśmy to dodać? 

btw, obgadujmy najpierw pomysły na channelu slackowym, żeby nie produkować ticketów ;)

**Comment by marcin-wosinek** [comment]
linki do eventów, w tabeli lub na liście; + np liczbą nowych osób na spotkaniu. Do mierzenia tej części działalności. Na stronie może być gdzieś zakopane głeboko.

@ btw, tikety mamy za darmo i póki jesteśmy dobrze poniżej 100 otwartych na raz można się w nich zorientować dość prosto. A pozwalają trzymać dyskuje 'blisko kodu' i prowadzić wiele równoległych wątków przez tygodnie

**Comment by agnespisz** [comment]
Na daną chwilę myślę, że powinniśmy to zostawić do wewnętrznego mierzenia, żeby nie robić bałaganu na stronie (i tak już jest tam dużo info ;) ).  Jak przyjdzie nam wizualizować postępy organizacji, to wtedy wykorzystamy zebrane info na temat do tej pory organizowanych spotkań/liczby osób. 

odnośnie ticketów - nie chodzi mi, że 'marnujemy tickety' - chodzi o to, że tylko my dwoje regularnie wchodzimy na github, a większość rzeczy pomysłowych warto obgadywać z osobami zaangażowanymi, które nie pracują na ticketach githubowych. Nawet ja wolę od razu odpisac na slacku, niż odpisywac w mailu na ticket z gita.
