### ISSUE TITLE
podstrona dla wsparcia organizacji

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#43]
https://trello.com/c/Vs3CNvyR/4-przygotowa%C4%87-podstron%C4%99-internetow%C4%85

**Comment by marcin-wosinek** [comment]
quick & dirty:
![czym-jest-ea](https://user-images.githubusercontent.com/1024920/34651142-775e3208-f3cc-11e7-9be8-bd4e6b2ab439.png)

Inne propozycjie mile widziane

**Comment by agnespisz** [comment]
przemyślimy, co potrzebujemy zakomunikować w tym temacie, i ewentualnie dopasujemy schemat strony.
