### ISSUE TITLE
tagi og

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#45]
title: ?
description: ?
image: (logo ?)

**Comment by agnespisz** [comment]
title: Efektywny Altruizm
description: Jesteśmy polską filią międzynarodowej społeczności Effective Altruism. Łączymy współczucie z dowodami naukowymi i racjonalnością, aby wytyczać najskuteczniejsze drogi poprawy świata, a potem nimi podążać.
image: sygnet logo, bez logotypu (czyli sama żarówka ;) )

**Comment by marcin-wosinek** [comment]
do wstawienia na:
https://github.com/eapoland/landing-page/blob/master/src/templates/layout.html#L17

**Comment by marcin-wosinek** [comment]
działające logo będzie do zrobienia po #49
