### ISSUE TITLE
add png logo for fb og:image

### ISSUE THREAD

**Issue by marcin-wosinek** [eapoland/landing-page#49]
600 x 600 &
1200 × 630
https://developers.facebook.com/docs/sharing/best-practices

**Comment by agnespisz** [comment]
ok wrzucam pliki do plików githubowych

**Comment by agnespisz** [comment]
![artboard 7-100](https://user-images.githubusercontent.com/32299247/35635024-788a245e-06ad-11e8-8a14-594bf7ca6d89.jpg)

**Comment by agnespisz** [comment]
![600x600 fb tag](https://user-images.githubusercontent.com/32299247/35635283-2c55b980-06ae-11e8-9d1b-d48f08556198.jpg)
