### ISSUE TITLE
links should have different colour 

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#8]
- words with links should be #0B91AA 
- on hover: they stay the same colour and are underlined

**Comment by marcin-wosinek** [comment]
Where there color should be applied?

1. in the menu:
![screenshot-2017-11-11 efektywny altruizm 1](https://user-images.githubusercontent.com/1024920/32688743-0abe910a-c6d7-11e7-8596-b2e58c83cc26.png)
2. normal text:
![screenshot-2017-11-11 efektywny altruizm 2](https://user-images.githubusercontent.com/1024920/32688776-941d18d6-c6d7-11e7-988e-be4e89f5c05c.png)

**Comment by agnespisz** [comment]
Yes, in both. 
in text is underlined only on mouse hover.

**Comment by marcin-wosinek** [comment]
ready to be checked at:
https://eapoland.github.io/landing-page/zacznij-dzialac.html

**Comment by agnespisz** [comment]
damn, sorry. In menu it should stay black, only on hover it gets color(and not underline).

**Comment by agnespisz** [comment]
also right now everything in the navbar is with turqoius :D

**Comment by marcin-wosinek** [comment]
top bar menu: as before
side menu: color on hover; no underline
text link: color; on hover underline

**Comment by agnespisz** [comment]
yes

**Comment by marcin-wosinek** [comment]
@agnespisz ready to be tested again

**Comment by agnespisz** [comment]
menu is fine but LOGO is colored still :)

**Comment by marcin-wosinek** [comment]
@agnespisz changed. please close if all is fine now:)
