### ISSUE TITLE
line-height for body - change for 1,5

### ISSUE THREAD

**Issue by agnespisz** [eapoland/landing-page#9]
NOW: 1,3
CHANGE FOR: 1,5

<img width="393" alt="screen shot 2017-10-30 at 10 29 46" src="https://user-images.githubusercontent.com/32299247/32163574-095628f6-bd5d-11e7-9a7f-53493ebf31b6.png">

**Comment by marcin-wosinek** [comment]
update & ready to be tested:
https://eapoland.github.io/landing-page/zacznij-dzialac.html

**Comment by marcin-wosinek** [comment]
I assume it's ok, please reopen or register new issue otherwise
